#!/usr/bin/env python3

name = input('Enter your name: ')
age = input('Enter your age: ')
# print('type of name', type(name))
# print('type of age', type(age))
# print('my name is ', name)
# print('My age is ', age)
# print('My name is %s and age is %s' %(name, age))
# print('my name is: {}, age: {}'.format(name, age))
# print('my name is: {1}, age: {0}'.format(age, name))
# print('my name is: {1}, age: {0}'.format(name, age))
# print('my name is: {n}, age: {a}'.format(n = name, a = age))
# print('my name is: {name}, age: {age}'.format(age = age, name=name))
print(f'my name is {name} and age is {age}')
